spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.0.69:3308/cloudDB01?useUnicode=true&characterEncoding=utf8             # 数据库名称
    username: root
    password: 123456
  session:
    store-type: none
#security:
#  basic:
#    enabled: false

#imooc:
#  security:
#    browser:
#      loginPage: /demo-signIn.html

